# Generated by Django 5.0.3 on 2024-03-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making_pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crust',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topping',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
