# Generated by Django 5.0.3 on 2024-03-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making_pizza', '0002_crust_notes_topping_notes_type_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
