# Generated by Django 5.0.3 on 2024-03-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('making_pizza', '0003_pizza_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
