# Generated by Django 5.0.3 on 2024-03-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making_pizza', '0005_alter_pizza_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='ratio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
