# Generated by Django 5.0.3 on 2024-03-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making_pizza', '0007_pizza_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='image',
            field=models.URLField(default='https://nomoneynotime.com.au/uploads/recipes/shutterstock_2042520416-1.jpg'),
            preserve_default=False,
        ),
    ]
