# Generated by Django 5.0.3 on 2024-03-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making_pizza', '0008_type_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
